<div class="row-fluid">
	<div class="span12" id="hero">
		<div class="inner">
			<h1>Msingi CMS</h1>

			<p class="lead">
				<?= $this->_('Zend Framework based CMS and application template') ?>
			</p>
		</div>
	</div>
</div>

<div class="row-fluid widgets">
	<div class="span4 widget">
		<?= $this->widget('frontpage-1') ?>
	</div>
	<div class="span4 widget">
		<?= $this->widget('frontpage-2') ?>
	</div>
	<div class="span4 widget">
		<?= $this->widget('frontpage-3') ?>
	</div>
</div>