<h1><?= $this->message ?></h1>

<?= $this->content ?>

<a href="javascript:history.back()" class="back_link btn btn-small"><?= $this->_('Go back') ?></a>

<?php if (isset($this->exception)) : ?>
	<h2><?= $this->_('Exception information') ?>:</h2>
	<p>
		<b><?= $this->_('Message') ?>:</b>
		<?php echo $this->exception->getMessage() ?>
	</p>

	<h3><?= $this->_('Stack trace') ?>:</h3>
	<pre><?php echo $this->exception->getTraceAsString() ?></pre>

	<h3><?= $this->_('Request Parameters') ?>:</h3>
	<pre><?php echo var_export($this->request->getParams(), true) ?></pre>
<?php endif; ?>

