<div id="tray" class="box">
	<p class="f-left box">
		<strong><?= $this->settings()->get('application:name') ?></strong>
	</p>
	<p class="f-right"><?= $this->_('User') ?>:
		<strong><?= Zend_Auth::getInstance()->getIdentity()->name ?></strong>
		<span class="spacer"> </span>
		<strong><a href="<?= $this->u('default:login:logout') ?>" id="logout"><?= $this->_('Log out') ?></a></strong>
	</p>
</div>
<hr class="noscreen" />
