<?php
$this->headLink()->appendStylesheet($this->assets() . '/css/2col.css');
?>
<?= $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?= $this->language() ?>" lang="<?= $this->language() ?>">
	<head>
		<?= $this->headMeta(); ?>
		<?= $this->headTitle(); ?>
		<?= $this->headLink(); ?>
		<?= $this->headLess(); ?>
		<?= $this->headStyle(); ?>
		<?= $this->headScript(); ?>
	</head>
	<body class="default">
		<div id="main">
			<?= $this->partial('partials/tray.phtml') ?>
			<?= $this->partial('partials/menu.phtml') ?>

			<div id="cols" class="box">
				<div id="aside" class="box">

					<div class="padding box">
						<p id="logo"><img src="<?= $this->assets() ?>/design/logo.gif" /></a></p>
					</div>

					<ul class="box">
						<?= $this->navigation()->menu()->setPartial(array('sidebar-menu.phtml', 'default'))->render(); ?>
					</ul>
				</div>
				<hr class="noscreen" />
				<div id="content" class="box">
					<?= $this->layout()->content ?>
				</div>
			</div>

			<?= $this->partial('partials/footer.phtml') ?>
		</div>
	</body>
</html>