<?= $this->doctype() ?>
<html lang="<?= $this->language() ?>">
	<head>
		<?= $this->headMeta(); ?>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<?= $this->headTitle(); ?>
		<?= $this->headLink(); ?>
		<?= $this->headLess(); ?>
		<?= $this->headStyle(); ?>
		<?= $this->headScript(); ?>
	</head>
	<body>
		<?= $this->partial('partials/navbar.phtml') ?>
		<div class="container" id="content">
			<?= $this->layout()->content ?>
		</div>
		<?= $this->partial('partials/footer.phtml') ?>
	</body>
</html>