<div class="paginator">
	<div class="span6">
		<?= $this->_s('Showing %d to %d of %d entries', $this->firstItemNumber, $this->lastItemNumber, $this->totalItemCount); ?>
	</div>
	<div class="span6">
		<div class="dataTables_paginate paging_bootstrap pagination">
			<ul>
				<?php if (isset($this->previous)): ?>
					<li class="prev"><a href="<?= $this->url(array('page' => $this->prev)); ?>"><?= $this->_('Previous') ?></a></li>
				<?php else : ?>
					<li class="prev disabled"><a href="#"><?= $this->_('Previous') ?></a></li>
				<?php endif; ?>

				<?php foreach ($this->pagesInRange as $page): ?>
					<?php if ($page == $this->current) : ?>
						<li class="active"><a href="#"><?= $page; ?></a></li>
					<?php else : ?>
						<li><a href="<?= $this->url(array('page' => $page)); ?>" class="paginate_button"><?= $page; ?></a></li>
					<?php endif; ?>
				<?php endforeach; ?>

				<?php if (isset($this->next)): ?>
					<li class="next"><a href="<?= $this->url(array('page' => $this->next)); ?>" class="next paginate_button"><?= $this->_('Next') ?></a></li>
				<?php else : ?>
					<li class="next disabled"><a href="#"><?= $this->_('Next') ?></a></li>
				<?php endif; ?>
			</ul>
		</div>
	</div>
</div>
